package:
  name: fast-transformers
  version: "0.1.1a0"

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler("cxx") }}  # [linux]
    - mkl-include
  run:
    - mkl
    - intel-openmp
    - pytorch
  host:
    - mkl
    - intel-openmp
